# Parameters for the example pipeline. Feel free to delete these once you
# remove the example pipeline from hooks.py and the example nodes in
# `src/pipelines/`
leadtime:
  min: 0
  max: 58
days:
  min: -30
  max: 59
kfolds:
  ctgan: 
    leadtime: CTGAN_leadtime
    days: CTGAN_days
  gc:
    leadtime: GC_leadtime
    days: CTGAN_days